FROM golang:1.14

RUN go get github.com/oxequa/realize

# files in current dir on host will be mount on /build without explicitly copying it as specified in docker-compose.yml
ENV APP_HOME /build

WORKDIR $APP_HOME

EXPOSE 4201

CMD [ "realize", "start", "--run" ]